server:
  port: 80
logging:
  level:
    ROOT: INFO
    web: INFO
  file:
    name: application.log
    path: ./logs
spring:
  session:
    # 15 minutes
    timeout: 900s
  redis:
    database: 1
    host: 127.0.0.1
    port: 6379
    username: redis
    password: redis
    connect-timeout: 10s
  application:
    name: "Hell Gate Core"
    admin:
      enabled: true
security:
  # 记住我功能，即开启 cookie 保存会话
  remember-me: true
  # 账号中心网址，这里是你的域名或服务器 IP 地址
  hub-url: "http://localhost"