website:
  author: "mrzhqiang"
  favicon: "/image/favicon.ico"
  title: "地狱之界"
  copy-right:  粤ICP备xxxxxxxx号 Copyright &copy; 2020 - 2020 ${website.author} 版权所有
  remember-me: false
  ignore-path:
    - /webjars/**
    - /css/**
    - /js/**
    - /image/**
    - /fontawesome/**
  public-path:
    - /
    - /index
    - /register
    - /register-help