server:
  port: 80

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hellgate?characterEncoding=utf-8&serverTimezone=Asia/Shanghai&autoReconnect=true
    username: root
    password: 12355..

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  thymeleaf:
    cache: false

  cache:
    type: simple

logging:
  level:
    web: DEBUG
  file:
    name: application.log

debug: true
