spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hellgate?characterEncoding=utf-8&serverTimezone=Asia/Shanghai&autoReconnect=true
    username: root
    password: 12355..

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update

  cache:
    type: redis

logging:
  level:
    web: INFO
  file:
    name: application.log
    path: logs

debug: false
