server:
  port: 80
logging:
  level:
    ROOT: DEBUG
    web: DEBUG
    # See http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#production-ready-endpoints
    org.springframework.boot.autoconfigure.security.AuthenticationManagerConfiguration: DEBUG
    # always log high-level information about application startup
    com.github.mrzhqiang.hellgate: DEBUG
  file:
    name: application.log
    path: ./logs
debug: true
spring:
  kaptcha:
    # 开发环境下屏蔽，线上建议打开
    enabled: false
  codec:
    log-request-details: ${debug}
  thymeleaf:
    cache: false
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  messages:
    basename: i18n.messages
    fallback-to-system-locale: false
  session:
    timeout: 5m
  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/hellgate?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false&allowMultiQueries=true
#    username: root
#    password: 123456
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:hellgate.db
  sql:
    init:
      mode: always
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  redis:
    database: 1
    host: 127.0.0.1
    port: 6379
    # username:
    password: 123456
website:
  # true 表示开启记住我功能，则可以在浏览器中保存 Cookie 用于一段时间内的免登录策略
  remember-me: false
http:
  # HTTP 请求客户端的缓存路径和限定大小
  cache-path: ${user.dir}/.cache
  cache-max-size: 100MB
