spring:
  profiles:
    active: dev
  messages:
    basename: i18n.messages,org.springframework.security.messages
    fallback-to-system-locale: false
website:
  author: "mrzhqiang"
  favicon: "/favicon.ico"
  title: "鬼门关"
  copy-right: 粤ICP备xxxxxxxx号 Copyright &copy; 2020 - 2022 ${website.author} 版权所有
  #  remember-me: false
  ignore-path:
    - "/fontawesome/**"
  public-path:
    - "/"
    - "/index"
    - "/register"
    - "/register/help"
    - "/error"
    - "/error/**"
  api-path: "/api/**"
  default-success-url: "/stage"
  login-path: "/login"
  register-path: "/register"
  register-error-path: "/register?error"
account:
  # 第一次登录失败距离现在的区间时长，当触发登录失败处理时，如果位于区间时长内，则累加失败次数；否则重置失败次数统计
  first-failed-duration: 1h
  # 最大登录失败次数
  max-login-failed: 5
  # 触发最大登录失败次数时，账户锁定的持续时长
  locked-duration: 5m