server:
  port: 80
logging:
  level:
    ROOT: INFO
    web: INFO
  file:
    name: application.log
    path: ./logs
spring:
  kaptcha:
    enabled: true
    config:
      kaptcha:
        border: "no"
        image:
          width: "150"
          height: "40"
        textproducer:
          font:
            color: "black"
            size: "30"
          char:
            space: "5"
            length: 4
    parameter: "kaptcha"
  # 账号中心是需要会话的，但不需要 Cookie 自动登录
  session:
    # 15 minutes
    timeout: 900s
  application:
    name: "Hell Gate Hub Prod"
    admin:
      enabled: true