server:
  port: 8080
logging:
  level:
    ROOT: INFO
    web: INFO
  file:
    name: application.log
    path: ./logs
spring:
  kaptcha:
    enabled: true
    config:
      kaptcha:
        border: "no"
        image:
          width: "150"
          height: "40"
        textproducer:
          font:
            color: "black"
            size: "30"
          char:
            space: "5"
            length: 4
    parameter: "kaptcha"
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  redis:
    database: 1
    host: 127.0.0.1
    port: 6379
    username: redis
    password: redis
    connect-timeout: 10s
  session:
    # 1 hours
    timeout: 3600s
  application:
    name: "Hell Gate Admin Prod"
    admin:
      enabled: true