spring:
  profiles:
    active: dev
    include:
      - common
  messages:
    basename: i18n.messages,org.springframework.security.messages
    fallback-to-system-locale: false
website:
  author: "287431404@qq.com"
  favicon: "/favicon.ico"
  title: "鬼门关后台管理系统"
  copy-right: 粤ICP备xxxxxxxx号 Copyright &copy; 2020 - 2022 ${website.author} 版权所有
security:
  remember-me: true
  public-path:
    - "/"
    - "/index"
    - "/error"
    - "/error/**"
  default-success-url: "/"
  login-path: "/login"
