server:
  port: 8888
logging:
  level:
    ROOT: INFO
    web: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
  file:
    name: application.log
    path: ./logs
spring:
  kaptcha:
    # 开发环境下屏蔽，线上建议打开
    enabled: true
    config:
      kaptcha:
        border: "no"
        image:
          width: "150"
          height: "40"
        textproducer:
          font:
            color: "black"
            size: "30"
          char:
            space: "5"
            length: 4
    parameter: "kaptcha"
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  redis:
    database: 1
    host: 127.0.0.1
    port: 6379
    username: redis
    password: redis
    connect-timeout: PT10S
security:
  remember-me: true