server:
  port: 8888
logging:
  level:
    ROOT: INFO
    web: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    # See http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#production-ready-endpoints
    org.springframework.boot.autoconfigure.security.AuthenticationManagerConfiguration: DEBUG
    # always log high-level information about application startup
    hellgate: DEBUG
debug: true
spring:
  kaptcha:
    # 开发环境下屏蔽，线上建议打开
    enabled: false
  codec:
    log-request-details: ${debug}
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  jpa:
    show-sql: true
  redis:
    database: 1
    host: 127.0.0.1
    port: 6379
    # username:
    password: 123456
security:
  # true 表示开启记住我功能，则可以在浏览器中保存 Cookie 用于一段时间内的免登录策略
  remember-me: false
http:
  client:
    # HTTP 请求客户端的缓存路径和限定大小
    cache-path: ${user.dir}/.cache
    cache-max-size: 100MB
