server:
  port: 80
logging:
  level:
    ROOT: INFO
    web: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    # See http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#production-ready-endpoints
    org.springframework.boot.autoconfigure.security.AuthenticationManagerConfiguration: DEBUG
    # always log high-level information about application startup
    hellgate: DEBUG
debug: true
spring:
  kaptcha:
    # 开发环境下屏蔽，线上建议打开
    enabled: false
  codec:
    log-request-details: ${debug}
  session:
    timeout: 5m
  redis:
    database: 1
    host: 127.0.0.1
    port: 6379
    password: 123456
  jpa:
    show-sql: true
http:
  client:
    # HTTP 请求客户端的缓存路径和限定大小
    cache-path: ${user.dir}/.cache
    cache-max-size: 100MB
