spring:
  profiles:
    active: dev
  messages:
    basename: i18n.messages,org.springframework.security.messages
    fallback-to-system-locale: false
website:
  author: "287431404@qq.com"
  favicon: "/favicon.ico"
  title: "鬼门关"
security:
  remember-me: true
  ignore-path:
  public-path:
    - "/"
    - "/index"
    - "/register"
    - "/register/help"
    - "/error/**"
  api-path: "/api/**"
  api-token-path: "/api/token"
  default-success-url: "/stage"
  login-path: "/login"
  register-path: "/register"
  register-error-path: "/register?error"
session:
  # 第一次登录失败距离现在的区间时长
  # 当触发登录失败处理时，如果位于区间时长内，则累加失败次数；否则重置失败次数统计
  first-failed-duration: 1h
  # 最大登录失败次数
  max-login-failed: 5
  # 触发最大登录失败次数时，账户锁定的持续时长
  locked-duration: 5m
  # 会话过期重定向地址
  expired-path: "/login?expired"
jwt:
  private-key: classpath:app.key
  public-key: classpath:app.pub
  expiry: 10h