spring:
  profiles:
    active: dev
    include:
      - common
  messages:
    basename: i18n.messages,org.springframework.security.messages
    fallback-to-system-locale: false
website:
  author: "287431404@qq.com"
  favicon: "/favicon.ico"
  title: "鬼门关"
  hotline: "客服电话: 150xxxxxxxx"
  groups:
    - "官方Q②群: 2xxxxxxxx"
    - "官方Q①群: 1xxxxxxxx"
security:
  public-path:
    - "/"
    - "/index"
    - "/home"
    - "/register/help"
    - "/error/**"
  login-path: "/login"
  login-failed-path: "/login?error"
  register-path: "/register"
  register-failed-path: "/register?error"
  default-success-url: "/script"
  bookmark-path: "/bookmark"
  # 若超过最大登录失败次数，账户将被锁定一段时间
  max-login-failed: 5
  # 在锁定区间内，无法进行登录操作
  locked-duration: 5m
  # 正常账户在首次登录失败时，将记录一个时间戳
  # 再次登录失败时，如果位于设定的区间时长内，则累加失败次数
  # 在账户未锁定时，登录成功将清除首次失败时间戳，并重置失败次数
  first-failed-duration: 1h
jwt:
  # ubuntu 命令生成私钥：openssl genrsa 2048 | openssl pkcs8 -topk8 -nocrypt -out app.key
  private-key: classpath:app.key
  # ubuntu 命令根据私钥生成公钥：openssl rsa -in app.key -pubout -outform PEM -out app.pub
  public-key: classpath:app.pub
  # 为了安全着想，书签 token 只能持续 30 天，超过 30 天将需要重新登录获取书签 token
  expiry: 30d
