@startmindmap
'https://plantuml.com/mindmap-diagram

title 暗黑之门--舞台 title

* 舞台
** 角色--玩家
*** 背包空间--角色私有，容纳：装备、饰品、道具、秘籍、货币等等
*** 装备
**** 头部1--冠、盔、巾、帽
**** 颈部1--项链
**** 肩部1--披风
**** 身体1--衣、袍……
**** 腰部1--腰带
**** 腿部1--裤、裙……
**** 脚部1--靴、鞋……
**** 手部4--手套、手镯、戒指、指环
**** 武器1&2--双手、左手、右手
*** 随从
**** 坐骑--属性加成
**** 宠物--协助打怪
*** 饰品
**** 耳环--通用技能
**** 勋章--佩戴消耗
**** 魔血--自动恢复
**** 图腾--增伤减伤
*** 道具
**** 经验卡--一次性消耗
**** 任务凭证--完成任务需要
**** 副本门票--开启副本使用
**** 宠物封印--获得对应的宠物
**** 宠物石头--属性加成
**** 宠物技能--公共技能：拾取、吃药、维修、挂机、经验增益
**** 装备打孔--针对装备进行打孔，用来镶嵌晶体
**** ……未完待续
*** 秘籍
**** 直接学习，修炼升级
**** 知识学习，直接升级
**** 残卷合成，条件升级
*** 货币
**** 金币--各种操作都需要消耗，出处：怪物、任务、礼包、出售
**** 白金--现金商店消费，仅交易一次，出处：充值、节假日活动、白金拍卖
**** 黑金--野外商店消费，无法交易，出处：日常活动、大boss、黑金地精、城堡门票收入
*** 药剂
**** 缓慢恢复--普通药
**** 瞬间回复--神药
**** 增益--buff
**** 抵消--圣药，抵消负面效果
*** 材料
**** 制作--打造装备，装备分解
***** 白装材料--凡尘之物
***** 蓝装材料--精妙之灵
***** 黄装材料--绝世之魂
***** 传奇材料--天地造化
***** 精英材料--日月精华
**** 凝练
***** 玄铁
***** 陨金
***** 秘银
***** 乌木
***** 龙骨
***** 凤皮
***** 钻石
***** 硫磺
***** 水晶
**** 附魔--转换一条不满意的凝练属性，可让原本神圣级别的装备，因转换而升级为混沌
**** 镶嵌--熔炼圣魂得到的晶体，可以镶嵌到装备之中
**** 锁魂--将使用者的灵魂绑定到装备，从而发挥最大的能力，需要
**** 抽奖--抽取对应位置的装备，来源大小米
*** 仓库--背包的增强版，账号公用
*** 能力
**** 基础属性
***** 等级
***** 经验值
***** 生命值
***** 魔法值
***** 攻击力
***** 魔力
***** 防御
***** 抗性
***** 主属性--力量、敏捷、智力、体能
***** 速度
****** 一回合默认2000ms，每100ms检测回合
****** 每100速度-10ms间隔，最高-1000ms间隔，即10000速度
***** 伤害加深--无上限
***** 伤害吸收--收益递减，最高99.9999%
**** 增益属性
***** 经验加成
***** 基础属性加成
***** 效果加成
*** 职业
**** 战士
**** 魔法师
**** 弓箭手
** 场景--地图
*** 安全区--活动、任务、休整、交易
*** 危险区--任务、挂机
*** 副本--层层递进，赢取荣耀

@endmindmap
