spring:
  profiles:
    active: dev
    include:
      - common
  messages:
    basename: i18n.messages,org.springframework.security.messages
    fallback-to-system-locale: false
website:
  author: "287431404@qq.com"
  favicon: "/favicon.ico"
  title: "鬼门关"
  copy-right: 粤ICP备xxxxxxxx号 Copyright &copy; 2020 - 2022 ${website.author} 版权所有
manage:
  security:
    remember-me: true
    public-path:
      - "/"
      - "/index"
      - "/admin"
      - "/error/**"
    default-success-url: "/"
    login-path: "/login"
    # 若超过最大登录失败次数，账户将被锁定一段时间
    max-login-failed: 5
    # 在锁定区间内，无法进行登录操作
    locked-duration: 5m
    # 正常账户在首次登录失败时，将记录一个时间戳
    # 再次登录失败时，如果位于设定的区间时长内，则累加失败次数
    # 在账户未锁定时，登录成功将清除首次失败时间戳，并重置失败次数
    first-failed-duration: 1h
