server:
  port: 8080
logging:
  level:
    org.springframework.security: DEBUG
    hellgate: DEBUG
  logback:
    rollingpolicy:
      clean-history-on-start: true
debug: true
#trace: true
spring:
  kaptcha:
    # 开发环境下屏蔽，线上建议打开
    enabled: false
  codec:
    log-request-details: true
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  jpa:
    show-sql: true
  redis:
    database: 1
    host: 127.0.0.1
    port: 6379
    # username:
    password: 123456
  application:
    name: "Hell Gate Admin Dev"
