@startmindmap
'https://plantuml.com/mindmap-diagram

title 初始化流程

* 准备进入管理后台首页
** 第一步 检测初始化表中是否存在未完成项目
*** 存在 执行第二步
*** 不存在 跳过初始化流程 进入管理后台首页
** 第二步 检测未完成项目中是否存在未完成任务
*** 存在 执行第三步
*** 不存在 设置当前初始化为已完成 回到第一步
** 第三步 根据未完成任务 设置对应的 ViewModel 实例返回
** 第四步 根据用户提交的初始化数据 执行对应初始化逻辑
** 第五步 设置当前任务编号为已完成 回到第一步

@endmindmap
